#!/bin/bash

your_command_string="sudo mv ~/Pictures/myscripts/fixcom /usr/local/bin/fixcom"
output=$(eval "$your_command_string")
echo "$output"
echo "Setup Completed!"

your_command_string="sudo chmod 755 /usr/local/bin/fixcom"
output=$(eval "$your_command_string")
echo "$output"
echo "Giving permissions Completed!"
